import os
from algosdk import account, mnemonic
from algosdk.v2client import algod
from algosdk.transaction import AssetConfigTxn

def mint_governance_token():
    # Localnet Configuration
    algod_address = "http://localhost:4001"
    algod_token = "a" * 64
    algod_client = algod.AlgodClient(algod_token, algod_address)

    # Get Default Localnet Account (Creator)
    # Using 'KMD' wallet is standard but tricky in script without proper setup.
    # Alternatively, use one of the accounts generated by `algokit localnet start`.
    # I'll rely on the user to provide an account mnemonic or try to fetch from kmd if possible.
    # For now, let's use a hardcoded mnemonic from a standard localnet if possible, OR
    # ask the user to provide their account.
    
    # Better: Use the same account as the deployment?
    # I'll try to find an account from KMD.
    from algosdk.kmd import KMDClient
    kmd = KMDClient("a"*64, "http://localhost:4002")
    wallets = kmd.list_wallets()
    default_wallet = [w for w in wallets if w['name'] == 'unencrypted-default-wallet'][0]
    wallet_token = kmd.init_wallet_handle(default_wallet['id'], "")
    addresses = kmd.list_keys(wallet_token)
    sender = addresses[0]
    private_key = kmd.export_key(wallet_token, "", sender)
    
    params = algod_client.suggested_params()

    # Create Asset
    txn = AssetConfigTxn(
        sender=sender,
        sp=params,
        total=1_000_000_000_000_000, # 1 billion * 10^6
        decimals=6,
        default_frozen=False,
        unit_name="CXG",
        asset_name="CarbonX Governance",
        manager=sender,
        reserve=sender,
        freeze=sender,
        clawback=sender,
        url="https://carbonx.local",
    )

    signed_txn = txn.sign(private_key)
    txid = algod_client.send_transaction(signed_txn)
    print(f"Transaction ID: {txid}")
    
    # Wait for confirmation
    results = algod_client.pending_transaction_info(txid)
    asset_id = results['asset-index']
    print(f"Created Asset: {asset_id}")
    return asset_id

if __name__ == "__main__":
    mint_governance_token()
